from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='Mkhayi Ltd.', max_length=200)),
                ('tagline', models.CharField(default='Your Trusted Security & Technology Partner', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('phone', models.CharField(default='+27 74 415 3970', max_length=30)),
                ('whatsapp_number', models.CharField(default='27744153970', max_length=30)),
                ('email', models.EmailField(default='info@mkhayi.co.za')),
                ('address', models.TextField(blank=True, default='South Africa')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('hero_heading', models.CharField(default='Protecting What Matters Most', max_length=120)),
                ('hero_subheading', models.TextField(default='Professional security services, CCTV supply & installation, and fibre connectivity across South Africa.')),
                ('hero_cta_label', models.CharField(default='Get a Free Quote', max_length=60)),
                ('hero_cta_secondary', models.CharField(default='Our Services', max_length=60)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('hero_image_overlay', models.DecimalField(decimal_places=2, default=0.55, max_digits=3)),
                ('about_heading', models.CharField(default='Built on Trust & Expertise', max_length=120)),
                ('about_body', models.TextField(default='Mkhayi Ltd. is a proudly South African company delivering integrated security and technology solutions.')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('about_image_caption', models.CharField(blank=True, default='Our team in the field', max_length=200)),
                ('about_years', models.PositiveIntegerField(default=5)),
                ('about_clients', models.PositiveIntegerField(default=500)),
                ('about_projects', models.PositiveIntegerField(default=800)),
                ('services_heading', models.CharField(default='What We Do', max_length=120)),
                ('services_subheading', models.TextField(blank=True, default='Comprehensive security and technology solutions tailored for residential and commercial clients.')),
                ('why_heading', models.CharField(default='Why Choose Mkhayi?', max_length=120)),
                ('why_body', models.TextField(default="We don't just sell products — we build lasting partnerships.")),
                ('why_image', models.ImageField(blank=True, null=True, upload_to='why/')),
                ('contact_heading', models.CharField(default="Let's Secure Your Future", max_length=120)),
                ('contact_subheading', models.TextField(blank=True, default='Reach out for a no-obligation quote. We respond within one business day.')),
                ('contact_image', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('meta_description', models.TextField(blank=True, default='Mkhayi Ltd. — security services, CCTV installation, and fibre connectivity across South Africa.')),
                ('meta_keywords', models.CharField(blank=True, default='security services, CCTV, fibre installation, South Africa', max_length=300)),
            ],
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('icon', models.CharField(choices=[('shield','Shield'),('camera','Camera'),('wifi','Wifi'),('lock','Lock'),('eye','Eye'),('wrench','Wrench'),('zap','Zap'),('globe','Globe'),('users','Users'),('activity','Activity')], default='shield', max_length=20)),
                ('highlight', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={'ordering': ['order', 'title'], 'verbose_name': 'Service'},
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, default='South Africa', max_length=100)),
                ('quote', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1,'1 stars'),(2,'2 stars'),(3,'3 stars'),(4,'4 stars'),(5,'5 stars')], default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('security','Security Services'),('cctv','CCTV Installations'),('fibre','Fibre Installations'),('general','General')], default='general', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={'ordering': ['order'], 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.CreateModel(
            name='WhyUsPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('icon', models.CharField(default='check', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={'ordering': ['order'], 'verbose_name': 'Why Us Point'},
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField()),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Contact Message'},
        ),
    ]
