# Generated by Django 4.2.29 on 2026-03-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='Min 800×600px', upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Two or three sentences describing this service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='highlight',
            field=models.CharField(blank=True, help_text='Short bold stat or selling point, e.g. "24/7 Active"', max_length=80),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('shield', 'Shield — Security'), ('camera', 'Camera — CCTV'), ('wifi', 'Wifi — Fibre / Network'), ('lock', 'Lock — Access Control'), ('eye', 'Eye — Monitoring'), ('wrench', 'Wrench — Maintenance'), ('zap', 'Zap — Electrical'), ('globe', 'Globe — Connectivity'), ('users', 'Users — Guarding'), ('activity', 'Activity — Response')], default='shield', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Service illustration — min 600×400px', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_body',
            field=models.TextField(default='Mkhayi Ltd. is a proudly South African company delivering integrated security and technology solutions. From armed response and CCTV systems to high-speed fibre installations, we cover everything your home or business needs to stay protected and connected. We combine industry expertise with honest, transparent service — so you always know exactly what you are getting.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_clients',
            field=models.PositiveIntegerField(default=500, help_text='Happy clients served'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Team or operations photo — min 800×600px', null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_projects',
            field=models.PositiveIntegerField(default=800, help_text='Installations completed'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_years',
            field=models.PositiveIntegerField(default=5, help_text='Years in operation'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_image',
            field=models.ImageField(blank=True, help_text='Background image for the contact strip', null=True, upload_to='contact/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='32×32 or 64×64 .ico / .png', null=True, upload_to='brand/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_heading',
            field=models.CharField(default='Protecting What Matters Most', help_text='Short punchy headline', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Full-width banner — min 1600×900px JPG/PNG', null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image_overlay',
            field=models.DecimalField(decimal_places=2, default=0.55, help_text='Overlay darkness 0.0 (none) to 1.0 (full black)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subheading',
            field=models.TextField(default='Professional security services, CCTV supply & installation, and fibre connectivity across South Africa.', help_text='One or two sentences shown below the headline'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Transparent PNG recommended, min 300px wide', null=True, upload_to='brand/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, default='security services, CCTV, fibre installation, South Africa, Mkhayi', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='services_subheading',
            field=models.TextField(blank=True, default='Comprehensive security and technology solutions tailored for residential and commercial clients across South Africa.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='27744153970', help_text='Digits only, no + or spaces. E.g. 27744153970', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='why_body',
            field=models.TextField(default="We don't just sell products — we build lasting partnerships. Every installation is backed by our experienced team, transparent pricing, and a commitment to after-sales support that keeps your systems running long after the first handshake."),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='why_image',
            field=models.ImageField(blank=True, help_text='Operatives or equipment photo — min 800×600px', null=True, upload_to='why/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Headshot — min 400×400px, square crop', null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, help_text='Client headshot — optional, 200×200px', null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='whyuspoint',
            name='icon',
            field=models.CharField(default='check', help_text='Icon name: check, star, shield, zap, users, clock, award, lock', max_length=20),
        ),
        migrations.AlterField(
            model_name='whyuspoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
